name: api_test
on: pull_request
jobs:
    commnet:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: read
        steps:
            - uses: actions/checkout@v6
            - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: echo "Comment posted"
    token_check:
        runs-on: ubuntu-latest
        steps:
            - run: echo "The GITHUB_TOKEN is set"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_TOKEN_2: ${{ github.token }}
            - run: echo "GITHUB_TOKEN $GITHUB_TOKEN"
            - run: echo "GITHUB_TOKEN_2 $GITHUB_TOKEN_2"